const SHELF_COLORS = [
    "#7f22fe", // DEFAULT
    "#6366F1",
    "#EC4899",
    "#10B981",
    "#F59E0B",
    "#EF4444",
    // "#8B5CF6",
    "#06B6D4",
    "#84CC16",
    "#F97316",
    "#64748B",
];

const GENRES = [
  "Action Thriller",
  "Action/Adventure Fiction",
  "Apocalyptic Sci-Fi",
  "Art & Photography",
  "Autobiography / Memoir",
  "Biography",
  "Body Horror",
  "Caper",
  "Children’s Fiction",
  "Classic Fiction",
  "Colonization Sci-Fi",
  "Comedy Horror",
  "Conspiracy Thriller",
  "Contemporary Fiction",
  "Contemporary Romance",
  "Cozy Mystery",
  "Dark Fantasy",
  "Dark Romance",
  "Disaster Thriller",
  "Erotic Romance",
  "Espionage Thriller",
  "Essays",
  "Fairy Tales",
  "Fantasy",
  "Fantasy Romance (Romantasy)",
  "Folktales",
  "Food & Drink",
  "Forensic Thriller",
  "Gothic Horror",
  "Gothic Romance",
  "Graphic Novel",
  "Gumshoe / Detective Mystery",
  "Hard Sci-Fi",
  "Heroic Fantasy",
  "High Fantasy",
  "Historical Fantasy",
  "Historical Fiction",
  "Historical Mystery",
  "Historical Romance",
  "Historical Thriller",
  "History",
  "Horror",
  "Howdunnit",
  "How-To / Guides",
  "Humanities & Social Sciences",
  "Humor",
  "Legal Thriller",
  "LGBTQ+",
  "Literary Fiction",
  "Locked Room Mystery",
  "Lovecraftian / Cosmic Horror",
  "Low Fantasy",
  "Magical Realism",
  "Military Sci-Fi",
  "Mind Uploading Sci-Fi",
  "Mystery",
  "Mythic Fantasy",
  "New Adult",
  "Noir",
  "Parallel World Sci-Fi",
  "Paranormal Horror",
  "Paranormal Romance",
  "Paranormal Thriller",
  "Parenting",
  "Philosophy",
  "Post-Apocalyptic Horror",
  "Procedural / Hard-Boiled Mystery",
  "Psychological Horror",
  "Psychological Thriller",
  "Quiet Horror",
  "Regency",
  "Religion & Spirituality",
  "Religious Thriller",
  "Romance",
  "Romantic Comedy",
  "Romantic Suspense",
  "Satire",
  "Science & Technology",
  "Science Fiction",
  "Sci-Fi Romance",
  "Self-Help",
  "Short Story",
  "Slasher",
  "Soft Sci-Fi",
  "Space Opera",
  "Space Western",
  "Steampunk",
  "Supernatural Mystery",
  "Thriller",
  "Travel",
  "True Crime",
  "Urban Fantasy",
  "Western",
  "Women’s Fiction",
  "Young Adult"
];


export { SHELF_COLORS, GENRES };
