const SHELF_COLORS = [
    "#7f22fe", // DEFAULT
    "#6366F1",
    "#EC4899",
    "#10B981",
    "#F59E0B",
    "#EF4444",
    // "#8B5CF6",
    "#06B6D4",
    "#84CC16",
    "#F97316",
    "#64748B",
];

const BOOK_GENRES = [
    { label: "Action thriller", value: "action_thriller" },
    { label: "Action/Adventure fiction", value: "action_adventure_fiction" },
    { label: "Apocalyptic sci-fi", value: "apocalyptic_sci_fi" },
    { label: "Art & photography", value: "art_photography" },
    { label: "Autobiography/Memoir", value: "autobiography_memoir" },
    { label: "Biography", value: "biography" },
    { label: "Body horror", value: "body_horror" },
    { label: "Caper", value: "caper" },
    { label: "Children’s fiction", value: "childrens_fiction" },
    { label: "Classic fiction", value: "classic_fiction" },
    { label: "Colonization sci-fi", value: "colonization_sci_fi" },
    { label: "Comedy horror", value: "comedy_horror" },
    { label: "Conspiracy thriller", value: "conspiracy_thriller" },
    { label: "Contemporary fiction", value: "contemporary_fiction" },
    { label: "Contemporary romance", value: "contemporary_romance" },
    { label: "Cozy mystery", value: "cozy_mystery" },
    { label: "Dark fantasy", value: "dark_fantasy" },
    { label: "Dark romance", value: "dark_romance" },
    { label: "Disaster thriller", value: "disaster_thriller" },
    { label: "Erotic romance", value: "erotic_romance" },
    { label: "Espionage thriller", value: "espionage_thriller" },
    { label: "Essays", value: "essays" },
    { label: "Fairy tales", value: "fairy_tales" },
    { label: "Fantasy", value: "fantasy" },
    { label: "Fantasy romance (Romantasy)", value: "fantasy_romance_romantasy" },
    { label: "Folktales", value: "folktales" },
    { label: "Food & drink", value: "food_drink" },
    { label: "Forensic thriller", value: "forensic_thriller" },
    { label: "Gothic horror", value: "gothic_horror" },
    { label: "Gothic romance", value: "gothic_romance" },
    { label: "Graphic novel", value: "graphic_novel" },
    { label: "Gumshoe/Detective mystery", value: "gumshoe_detective_mystery" },
    { label: "Hard sci-fi", value: "hard_sci_fi" },
    { label: "Heroic fantasy", value: "heroic_fantasy" },
    { label: "High fantasy", value: "high_fantasy" },
    { label: "Historical fantasy", value: "historical_fantasy" },
    { label: "Historical fiction", value: "historical_fiction" },
    { label: "Historical mystery", value: "historical_mystery" },
    { label: "Historical romance", value: "historical_romance" },
    { label: "Historical thriller", value: "historical_thriller" },
    { label: "History", value: "history" },
    { label: "Horror", value: "horror" },
    { label: "Howdunnits", value: "howdunnits" },
    { label: "How-To/Guides", value: "how_to_guides" },
    { label: "Humanities & social sciences", value: "humanities_social_sciences" },
    { label: "Humor", value: "humor" },
    { label: "Legal thriller", value: "legal_thriller" },
    { label: "LGBTQ+", value: "lgbtq" },
    { label: "Literary fiction", value: "literary_fiction" },
    { label: "Locked room mystery", value: "locked_room_mystery" },
    { label: "Lovecraftian/Cosmic horror", value: "lovecraftian_cosmic_horror" },
    { label: "Low fantasy", value: "low_fantasy" },
    { label: "Magical realism", value: "magical_realism" },
    { label: "Military sci-fi", value: "military_sci_fi" },
    { label: "Mind uploading sci-fi", value: "mind_uploading_sci_fi" },
    { label: "Mystery", value: "mystery" },
    { label: "Mythic fantasy", value: "mythic_fantasy" },
    { label: "New adult", value: "new_adult" },
    { label: "Noir", value: "noir" },
    { label: "Parallel world sci-fi", value: "parallel_world_sci_fi" },
    { label: "Paranormal horror", value: "paranormal_horror" },
    { label: "Paranormal romance", value: "paranormal_romance" },
    { label: "Paranormal thriller", value: "paranormal_thriller" },
    { label: "Parenting", value: "parenting" },
    { label: "Philosophy", value: "philosophy" },
    { label: "Post-apocalyptic horror", value: "post_apocalyptic_horror" },
    { label: "Procedural/Hard-boiled mystery", value: "procedural_hard_boiled_mystery" },
    { label: "Psychological horror", value: "psychological_horror" },
    { label: "Psychological thriller", value: "psychological_thriller" },
    { label: "Quiet horror", value: "quiet_horror" },
    { label: "Regency", value: "regency" },
    { label: "Religion & spirituality", value: "religion_spirituality" },
    { label: "Religious thriller", value: "religious_thriller" },
    { label: "Romance", value: "romance" },
    { label: "Romantic comedy", value: "romantic_comedy" },
    { label: "Romantic suspense", value: "romantic_suspense" },
    { label: "Satire", value: "satire" },
    { label: "Science & technology", value: "science_technology" },
    { label: "Science fiction", value: "science_fiction" },
    { label: "Sci-fi romance", value: "sci_fi_romance" },
    { label: "Self-help", value: "self_help" },
    { label: "Short story", value: "short_story" },
    { label: "Slasher", value: "slasher" },
    { label: "Soft sci-fi", value: "soft_sci_fi" },
    { label: "Space opera", value: "space_opera" },
    { label: "Space western", value: "space_western" },
    { label: "Steampunk", value: "steampunk" },
    { label: "Supernatural mystery", value: "supernatural_mystery" },
    { label: "Thriller", value: "thriller" },
    { label: "Travel", value: "travel" },
    { label: "True crime", value: "true_crime" },
    { label: "Urban fantasy", value: "urban_fantasy" },
    { label: "Western", value: "western" },
    { label: "Women’s fiction", value: "womens_fiction" },
    { label: "Young adult", value: "young_adult" }
];


const BOOK_FORMATS = [
  { label: "Hardcover", value: "HARDCOVER" },
  { label: "Paperback", value: "PAPERBACK" },
  { label: "eBook", value: "EBOOK" },
  { label: "Audiobook", value: "AUDIOBOOK" },
];

const BOOK_STATUSES = [
  { label: "TBR", value: "TBR" },
  { label: "Reading", value: "READING" },
  { label: "Read", value: "READ" },
  { label: "Paused", value: "PAUSED" },
  { label: "DNF", value: "DNF" },
];

export { SHELF_COLORS, BOOK_GENRES, BOOK_FORMATS, BOOK_STATUSES };
